package com.meowkings.witch_atelier.world.tree;

import com.meowkings.witch_atelier.registries.WitchAtelierModTreePlacers;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.BlockPos;
import net.minecraft.util.RandomSource;
import net.minecraft.util.valueproviders.IntProvider;
import net.minecraft.world.level.LevelSimulatedReader;
import net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration;
import net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacer;
import net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacerType;

public final class SilverwoodFoliagePlacer extends FoliagePlacer {
    public static final MapCodec<SilverwoodFoliagePlacer> CODEC = RecordCodecBuilder.mapCodec(instance -> foliagePlacerParts(instance).apply(instance, SilverwoodFoliagePlacer::new));

    public SilverwoodFoliagePlacer(IntProvider radius, IntProvider offset) {
        super(radius, offset);
    }

    @Override
    protected FoliagePlacerType<?> type() {
        return WitchAtelierModTreePlacers.SILVERWOOD_FOLIAGE_PLACER.get();
    }

    @Override
    protected void createFoliage(LevelSimulatedReader level, FoliageSetter blockSetter, RandomSource random, TreeConfiguration config, int maxFreeTreeHeight, FoliageAttachment attachment, int foliageHeight, int foliageRadius, int offset) {
        BlockPos origin = attachment.pos();

        placeLeaf(level, blockSetter, random, config, origin, 0, 4, -1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 4, -1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 4, 0);
        placeLeaf(level, blockSetter, random, config, origin, 2, 4, 0);
        placeLeaf(level, blockSetter, random, config, origin, -1, 4, 1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 4, 1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 4, 1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 4, 2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 4, 2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 5, -2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 5, -2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 5, -1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 5, -1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 5, -1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 5, -1);
        placeLeaf(level, blockSetter, random, config, origin, -2, 5, 0);
        placeLeaf(level, blockSetter, random, config, origin, -1, 5, 0);
        placeLeaf(level, blockSetter, random, config, origin, 2, 5, 0);
        placeLeaf(level, blockSetter, random, config, origin, 3, 5, 0);
        placeLeaf(level, blockSetter, random, config, origin, -2, 5, 1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 5, 1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 5, 1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 5, 1);
        placeLeaf(level, blockSetter, random, config, origin, -2, 5, 2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 5, 2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 5, 2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 5, 2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 5, 3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, -4);
        placeLeaf(level, blockSetter, random, config, origin, -2, 6, -3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, -3);
        placeLeaf(level, blockSetter, random, config, origin, 0, 6, -3);
        placeLeaf(level, blockSetter, random, config, origin, 2, 6, -3);
        placeLeaf(level, blockSetter, random, config, origin, 3, 6, -3);
        placeLeaf(level, blockSetter, random, config, origin, -3, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, 3, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, 4, 6, -2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 6, -1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 6, -1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 6, -1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 6, -1);
        placeLeaf(level, blockSetter, random, config, origin, 4, 6, -1);
        placeLeaf(level, blockSetter, random, config, origin, -3, 6, 0);
        placeLeaf(level, blockSetter, random, config, origin, -2, 6, 0);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, 0);
        placeLeaf(level, blockSetter, random, config, origin, 2, 6, 0);
        placeLeaf(level, blockSetter, random, config, origin, 3, 6, 0);
        placeLeaf(level, blockSetter, random, config, origin, -2, 6, 1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, 1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 6, 1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 6, 1);
        placeLeaf(level, blockSetter, random, config, origin, -3, 6, 2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 6, 2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, 2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 6, 2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 6, 2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 6, 2);
        placeLeaf(level, blockSetter, random, config, origin, 3, 6, 2);
        placeLeaf(level, blockSetter, random, config, origin, -3, 6, 3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, 3);
        placeLeaf(level, blockSetter, random, config, origin, 0, 6, 3);
        placeLeaf(level, blockSetter, random, config, origin, 1, 6, 3);
        placeLeaf(level, blockSetter, random, config, origin, 2, 6, 3);
        placeLeaf(level, blockSetter, random, config, origin, 3, 6, 3);
        placeLeaf(level, blockSetter, random, config, origin, -3, 6, 4);
        placeLeaf(level, blockSetter, random, config, origin, -2, 6, 4);
        placeLeaf(level, blockSetter, random, config, origin, -1, 6, 4);
        placeLeaf(level, blockSetter, random, config, origin, 0, 6, 4);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, -4);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, -4);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, -4);
        placeLeaf(level, blockSetter, random, config, origin, 2, 7, -4);
        placeLeaf(level, blockSetter, random, config, origin, 3, 7, -4);
        placeLeaf(level, blockSetter, random, config, origin, -3, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, 1, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, 2, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, 3, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, -3);
        placeLeaf(level, blockSetter, random, config, origin, -3, 7, -2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, -2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, -2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 7, -2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 7, -2);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, -2);
        placeLeaf(level, blockSetter, random, config, origin, 5, 7, -2);
        placeLeaf(level, blockSetter, random, config, origin, -4, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, -3, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, 5, 7, -1);
        placeLeaf(level, blockSetter, random, config, origin, -4, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, -3, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, 2, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, 3, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, 0);
        placeLeaf(level, blockSetter, random, config, origin, -3, 7, 1);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, 1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, 1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 7, 1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 7, 1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 7, 1);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, 1);
        placeLeaf(level, blockSetter, random, config, origin, -3, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, 3, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, 5, 7, 2);
        placeLeaf(level, blockSetter, random, config, origin, -3, 7, 3);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, 3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, 3);
        placeLeaf(level, blockSetter, random, config, origin, 0, 7, 3);
        placeLeaf(level, blockSetter, random, config, origin, 1, 7, 3);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, 3);
        placeLeaf(level, blockSetter, random, config, origin, 5, 7, 3);
        placeLeaf(level, blockSetter, random, config, origin, -2, 7, 4);
        placeLeaf(level, blockSetter, random, config, origin, -1, 7, 4);
        placeLeaf(level, blockSetter, random, config, origin, 1, 7, 4);
        placeLeaf(level, blockSetter, random, config, origin, 2, 7, 4);
        placeLeaf(level, blockSetter, random, config, origin, 3, 7, 4);
        placeLeaf(level, blockSetter, random, config, origin, 4, 7, 4);
        placeLeaf(level, blockSetter, random, config, origin, -2, 8, -3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 8, -3);
        placeLeaf(level, blockSetter, random, config, origin, 0, 8, -3);
        placeLeaf(level, blockSetter, random, config, origin, 1, 8, -3);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, -3);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, -3);
        placeLeaf(level, blockSetter, random, config, origin, -3, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, 4, 8, -2);
        placeLeaf(level, blockSetter, random, config, origin, -3, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, -2, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, 4, 8, -1);
        placeLeaf(level, blockSetter, random, config, origin, -3, 8, 0);
        placeLeaf(level, blockSetter, random, config, origin, -2, 8, 0);
        placeLeaf(level, blockSetter, random, config, origin, 0, 8, 0);
        placeLeaf(level, blockSetter, random, config, origin, 1, 8, 0);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, 0);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, 0);
        placeLeaf(level, blockSetter, random, config, origin, -2, 8, 1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 8, 1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 8, 1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, 1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, 1);
        placeLeaf(level, blockSetter, random, config, origin, -3, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, 4, 8, 2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 8, 3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 8, 3);
        placeLeaf(level, blockSetter, random, config, origin, 0, 8, 3);
        placeLeaf(level, blockSetter, random, config, origin, 1, 8, 3);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, 3);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, 3);
        placeLeaf(level, blockSetter, random, config, origin, 4, 8, 3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 8, 4);
        placeLeaf(level, blockSetter, random, config, origin, 2, 8, 4);
        placeLeaf(level, blockSetter, random, config, origin, 3, 8, 4);
        placeLeaf(level, blockSetter, random, config, origin, -2, 9, -2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 9, -2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 9, -2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 9, -2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 9, -2);
        placeLeaf(level, blockSetter, random, config, origin, 3, 9, -2);
        placeLeaf(level, blockSetter, random, config, origin, -2, 9, -1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 9, -1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 9, -1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 9, -1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 9, -1);
        placeLeaf(level, blockSetter, random, config, origin, 3, 9, -1);
        placeLeaf(level, blockSetter, random, config, origin, -2, 9, 0);
        placeLeaf(level, blockSetter, random, config, origin, -1, 9, 0);
        placeLeaf(level, blockSetter, random, config, origin, 0, 9, 0);
        placeLeaf(level, blockSetter, random, config, origin, 1, 9, 0);
        placeLeaf(level, blockSetter, random, config, origin, 2, 9, 0);
        placeLeaf(level, blockSetter, random, config, origin, -2, 9, 1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 9, 1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 9, 1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 9, 1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 9, 1);
        placeLeaf(level, blockSetter, random, config, origin, -2, 9, 2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 9, 2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 9, 2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 9, 2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 9, 2);
        placeLeaf(level, blockSetter, random, config, origin, 3, 9, 2);
        placeLeaf(level, blockSetter, random, config, origin, -1, 9, 3);
        placeLeaf(level, blockSetter, random, config, origin, 0, 9, 3);
        placeLeaf(level, blockSetter, random, config, origin, 2, 9, 3);
        placeLeaf(level, blockSetter, random, config, origin, 3, 9, 3);
        placeLeaf(level, blockSetter, random, config, origin, -1, 10, -1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 10, -1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 10, -1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 10, -1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 10, 0);
        placeLeaf(level, blockSetter, random, config, origin, 0, 10, 0);
        placeLeaf(level, blockSetter, random, config, origin, 1, 10, 0);
        placeLeaf(level, blockSetter, random, config, origin, 2, 10, 0);
        placeLeaf(level, blockSetter, random, config, origin, -1, 10, 1);
        placeLeaf(level, blockSetter, random, config, origin, 0, 10, 1);
        placeLeaf(level, blockSetter, random, config, origin, 1, 10, 1);
        placeLeaf(level, blockSetter, random, config, origin, 2, 10, 1);
        placeLeaf(level, blockSetter, random, config, origin, -1, 10, 2);
        placeLeaf(level, blockSetter, random, config, origin, 0, 10, 2);
        placeLeaf(level, blockSetter, random, config, origin, 1, 10, 2);
        placeLeaf(level, blockSetter, random, config, origin, 2, 10, 2);
    }

    @Override
    public int foliageHeight(RandomSource random, int height, TreeConfiguration config) {
        return 7;
    }

    @Override
    protected boolean shouldSkipLocation(RandomSource random, int localX, int localY, int localZ, int range, boolean large) {
        return false;
    }

    private void placeLeaf(LevelSimulatedReader level, FoliageSetter blockSetter, RandomSource random, TreeConfiguration config, BlockPos origin, int x, int y, int z) {
        tryPlaceLeaf(level, blockSetter, random, config, origin.offset(x, y, z));
    }
}
